s="Aarohi Gadhavi"

print(len(s))
print(s)
print(s.capitalize())
print(s.casefold())
print(s.upper())
print(s.lower())
print(s.swapcase())
print(s.center(40,"*"))
print(s.count("T"))
print(s.endswith("vi"))
print(s.startswith("Aa"))
print(s.find("dha"))
print(s.index("a",2))
print("tops123".isalnum())
print("tops".isalpha())
print("123".isnumeric())
print(" ".isspace())
print(s.istitle())
print("TOPS".isupper())
print("Tops".islower())
print(s.replace("o","a"))
